# Generated by Django 5.1.2 on 2024-12-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='burn',
            field=models.BooleanField(default=False),
        ),
    ]
